branch-defaults:
  default:
    environment: sample-env
    group_suffix: null
global:
  application_name: docker-single-container-1-example
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Docker 1.12.6
  default_region: us-west-2
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
